SocialNetworkAPI_JS:
    pattern:  /js/{js}
    defaults: { _controller: SocialNetworkAPI:Resources:getJS }
    requirements:
            _method:  GET

SocialNetworkAPI_EJS:
    pattern:  /ejs/{ejs}
    defaults: { _controller: SocialNetworkAPI:Resources:getEJS }
    requirements:
            _method:  GET
API_user_me:
    pattern:  /user/me
    defaults: { _controller: SocialNetworkAPI:Resources:userMe }
    requirements:
            _method:  GET

API_user_add:
    pattern:  /addUser
    defaults: { _controller: SocialNetworkAPI:Resources:addUser }
    requirements:
        _method:  POST

API_user_edit:
    pattern:  /editUser
    defaults: { _controller: SocialNetworkAPI:Resources:editUser }
    requirements:
        _method:  PUT

API_user_search:
    pattern:  /searchUser/{keyWord}
    defaults: { _controller: SocialNetworkAPI:Resources:searchUser }
    requirements:
            _method:  GET