social_network_profile_index:
    pattern:  /{uid}
    defaults: { _controller: SocialNetworkProfileBundle:Profile:index }
    requirements:
            _method:  GET

social_network_profile:
    pattern:  /profile/{uid}
    defaults: { _controller: SocialNetworkProfileBundle:Profile:user }
    requirements:
            _method:  GET

social_network_visitor:
    pattern:  /visitor
    defaults: { _controller: SocialNetworkProfileBundle:Profile:visitor }
    requirements:
            _method:  POST

social_network_album:
    pattern:  /album
    defaults: { _controller: SocialNetworkProfileBundle:Album:add }
    requirements:
            _method:  POST

social_network_album_cover:
    pattern:  /album/cover/{album}/{photo}
    defaults: { _controller: SocialNetworkProfileBundle:Album:addCover }
    requirements:
            _method:  PUT

social_network_photo_add:
    pattern:  /photo
    defaults: { _controller: SocialNetworkProfileBundle:Photo:add }
    requirements:
            _method:  POST

social_network_photo_delete:
    pattern:  /photo/{album}/{photo}
    defaults: { _controller: SocialNetworkProfileBundle:Photo:delete }
    requirements:
            _method:  DELETE

social_network_photo_profile:
    pattern:  /photoProfile
    defaults: { _controller: SocialNetworkProfileBundle:Photo:addPhotoProfile }
    requirements:
            _method:  POST

social_network_current_photo_profile:
    pattern:  /currentPhotoProfile
    defaults: { _controller: SocialNetworkProfileBundle:Photo:currentPhotoProfile }
    requirements:
           _method:  GET

social_network_photo_by_album:
    pattern:  /album/{albumName}/{userId}
    defaults: { _controller: SocialNetworkProfileBundle:Photo:listPhotoByAlbum }
    requirements:
            _method:  GET

social_network_change_photo_profile:
    pattern: /change/photo/profile/{photo}
    defaults: { _controller: SocialNetworkProfileBundle:Photo:changePhotoProfile }
    requirements:
            _method:  PUT