social_network_profile_index:
    pattern:  /{uid}
    defaults: { _controller: SocialNetworkProfileBundle:Profile:index }
    requirements:
            _method:  GET

social_network_profile:
    pattern:  /profile/{uid}
    defaults: { _controller: SocialNetworkProfileBundle:Profile:user }
    requirements:
            _method:  GET

social_network_visitor:
    pattern:  /visitor
    defaults: { _controller: SocialNetworkProfileBundle:Profile:visitor }
    requirements:
            _method:  POST

social_network_album:
    pattern:  /album
    defaults: { _controller: SocialNetworkProfileBundle:Album:add }
    requirements:
            _method:  POST

social_network_album:
    pattern:  /photo
    defaults: { _controller: SocialNetworkProfileBundle:Photo:add }
    requirements:
            _method:  POST